language: ruby

rvm:
 - 2.2.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx
