# === 网站基础信息 ===
title: 蒼璃                             # 网站标题，将显示在导航栏和浏览器标题中
bio: 热爱技术，热爱生活                # 简短介绍，显示在主页
description: A blog about technology and stuff related  # 用于 SEO 和社交媒体摘要

# === 头像配置 ===
external-image: false                   # 如果头像使用外部链接，这里设为 true
picture: assets/images/github.jpg       # 头像图片路径，建议使用方形图像

# === 主题模式 ===
dark-theme: auto                        # 网站主题：true（强制深色）/ false（强制浅色）/ auto（随系统切换）

# === 简历页面配置 ===
resume: true                            # 是否启用简历链接
resume-external: true                   # 是否使用外部链接方式打开简历
resume-url: https://google.com/?q=my+resume  # 简历链接地址（外部链接）

# === 站点 URL 与文章链接样式 ===
url: https://s0raLin.github.io          # 站点部署地址（请改为你的 GitHub Pages 地址）
permalink: /:title/                     # 设置文章永久链接格式，如 /my-post-title/

# === Google 分析（可选）===
# analytics-google: 'UA-XXXXXXXXX'      # 启用 Google Analytics，填写你的追踪 ID

# === Disqus 评论系统配置 ===
disqus:
  shortname: github                     # 你的 Disqus 帐号短名称
  categories: [blog, project]           # 启用评论的文章类别（这些类别的文章才有评论框）

# === 社交平台信息（不需要可注释掉） ===
facebook: myfacebook
twitter: mytwitter
instagram: myinstagram
linkedin: mylinkedin
github: mygithub
email: myemail@gmail.com

# === 多作者配置（可选）===
authors:
  johndoe:
    name: John Doe
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/github.jpg
    twitter: johndoe
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/github.jpg
    twitter: jamesfoster

# === 网站宽度 ===
# 可选值: normal（560px）或 large（810px）
width: normal

# === 功能模块开关 ===
projects: true                          # 是否启用“项目”页面
about: true                             # 是否启用“关于我”页面
blog: true                              # 是否启用“博客”页面

# === 文章显示配置 ===
read-time: true                         # 是否显示阅读时间
show-tags: true                         # 是否显示标签
related: true                           # 是否显示相关文章
post-advance-links: [blog]              # 博客文章页底部显示前后文章导航
show-author: true                       # 是否在文章末尾显示作者信息
animation: true                         # 是否启用页面过渡动画

# === 默认 Front Matter 设置（应用于所有文章）===
defaults:
  - scope:
      path: ""                          # 空字符串表示对所有路径生效
      layout: "post"                    # 默认使用 post 布局
    values:
      hidden: false                     # 所有文章默认不隐藏（可单独在 Front Matter 覆盖）

# === Jekyll 插件（功能扩展）===
plugins:
  - jekyll-seo-tag                      # 添加 SEO 支持标签
  - jekyll-gist                         # 支持嵌入 GitHub Gist
  - jekyll-feed                         # 自动生成 RSS Feed
  - jemoji                              # 支持 GitHub 风格 Emoji 表情

# === HTML 压缩配置 ===
compress_html:
  ignore:
    envs:
      - development                     # 开发环境下不压缩
      - stage                           # staging 环境也不压缩

# === 构建时排除的文件或目录 ===
exclude:
  - "README.md"                         # 不构建 README.md 文件
  - "Gemfile"                           # 不构建 Gemfile
  - "Gemfile.lock"
  - "FAQ.md"
  - "vendor"                            # 排除 vendor 目录（通常是第三方库）

