# main text of home
title: ind. aoibhinn nic aoidh
bio: it's pronounced a-veen

# twitter summary info
description: it's pronounced a-veen

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://aoibh.in
# your url: https://USERNAME.github.io

permalink: /:title/

# if you don't have any of social below, comment the line
facebook: oibind
twitter: oibind
instagram: oibind
flickr: oibind
linkedin: oibind
github: oibind
hackerrank: oibind
reddit: oibind
medium: oibind
email: oibind@pm.me
keybase: oibind
tumblr: oibind
paypal: oibind
monero: 4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbS1dRcHUafJvJu34MwD

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
