name: Jekyll Deploy

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build & Deploy to GitHub Pages
              env:
                  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
                  GITHUB_ACTOR: ${{ github.GITHUB_ACTOR }}
              uses: sylvainmetayer/jekyll-deploy-gh-pages@master
